from string import Template
import random

class CheeseCommand(object):

	def __init__(self):

		self.templates = [ 	Template("begrudgingly serves $name $snack."),
							Template("slices up some $cheese with the wrong end of the knife. Punts it to $name."),
							Template("fists a pile of $cheese and smears it on a napkin. Teases $name with it."),
							Template("breaks out a new packet of $cheese. Thinks it's too good for $name, puts it away."),
							Template("looks at $name and bakes up a box of $cheese."),
							Template("thinks that $cheese is best for $name. They both stink."),
							Template("pulls out glob of $cheese. Rubs it across a plate for $name"),
							Template("winks and produces some $cheese from under the counter for $name"),
							Template("cries, it was $cheese caused his wife to leave him. $name is barred"),
							Template("demands cash up front before giving $name a slither of $cheese"),
							Template("throws a pound of $cheese at $name. 'That is for Britain', he shouts."),
							Template("is read to give it all up and move to France, living off $cheese."),
							Template("empties his pockets, and a musty lump of $cheese falls out. $name snaffles it up."),
							Template("peels back the wax paper from the $cheese. Powers it across the bar to $name.") ]

		self.snacks = [ "Bath Blue",
			"Barkham Blue",
			"Blue Monday",
			"Buxton Blue",
			"Cheshire Blue",
			"Devon Blue",
			"Dorset Blue Vinney",
			"Dovedale",
			"Exmoor Blue",
			"Harbourne Blue",
			"Lanark Blue",
			"Oxford Blue",
			"Shropshire Blue",
			"Stichelton",
			"Stilton",
			"Blue Wensleydale",
			"Yorkshire Blue",
			"Appledore",
			"Berkswell",
			"Bonchester",
			"Brie",
			"Somerset Brie",
			"Cornish Brie",
			"Brinkburn",
			"Caithness",
			"Caboc",
			"Caerphilly",
			"Cheddar",
			"West Country Farmhouse Cheddar",
			"Applewood",
			"Coleraine cheddar",
			"Cheshire",
			"Appleby Cheshire",
			"Chevington",
			"Coquetdale",
			"Cornish Pepper",
			"Cotherstone",
			"Cotswold",
			"Coverdale",
			"Croglin",
			"Crowdie",
			"Derby",
			"Double Gloucester",
			"Goosnargh Gold",
			"Dorstone",
			"Dovedale",
			"Dunlop",
			"Farleigh Wallop",
			"Farmhouse Llanboidy",
			"Fine Fettle Yorkshire",
			"Goldilocks",
			"Black Eyed Susan",
			"Golden Cross",
			"Gruth Dhu",
			"Harlech",
			"Hereford Hop",
			"Huntsman",
			"Ilchester",
			"Innkeepers Choice",
			"Isle of Mull",
			"Lancashire",
			"Beacon Fell",
			"Lincolnshire Poacher",
			"Little Wallop",
			"Katy's White Lavender",
			"Kidderton Ash",
			"Lord of the Hundreds",
			"Lowerdale Goats Cheese",
			"Pantysgawn",
			"Parlick Fell",
			"Red Devil",
			"Red Dragon",
			"Red Leicester",
			"Rothbury Red",
			"Red Windsor",
			"Sage Derby",
			"Single Gloucester",
			"Stinking Bishop",
			"Sussex Slipcote",
			"Swaledale",
			"Teviotdale",
			"Tintern",
			"Waterloo",
			"Wensleydale",
			"Whitehaven",
			"Yarg",
			"Wild Garlic Yarg",
			"Wiltshire Loaf",
			"Woolsery Goats",
			"Village Green Goat",
			"Brunost",
			"Gamalost",
			"Geitost",
			"Gudbrandsdalsost",
			"Jarlsberg",
			u'Nøkkelost',
			"Norvegia",
			"Pultost",
			u'Snøfrisk',
			"Edam",
			"Gouda",
			"Leerdammer",
			"Leyden cheese",
			"Maasdam",
			"Old Amsterdam",
			"Parrano",
			"Vlaskaas",
			"Camembert",
			"Brie de Meaux",
			"Roquefort",
			"Boursin",
			"Reblochon",
			"Munster",
			"Pont l'Évêque",
			"Époisses",
			"Chèvre",
			"Tomme de Savoie",
			"Y Fenni", ]

	def execute( self, message ):
		cheese = random.choice( self.cheese )
		name = message.FromDisplayName
		template = random.choice( self.templates )
		message_out = template.substitute(name=name, cheese=cheese)
		return "/me %s" % message_out
