# coding=UTF-8

from string import Template
import random
import commandbase

class ChoonCommand( commandbase.BaseCommand ):

    def __init__(self):

        self.templates = [  Template("does a rubbish swan-dive and puts on some $choon for $name"),
                            Template("slides along the bar and points at $name. Obviously, it has to be $choon"),
                            Template("puts on the bestof $choon DVD. Noting this is totally $name."),
                            Template("picks up the harmonica and plays a sad song."),
                            Template("picks up the guitar and plays a traditional flamenco badly."),
                            Template("slides over to the piano and plays chopstiks like a loon."),
                            Template("picks up the drum sticks and performs Lady in Red"),
                            Template("grabs a pair of spoons and attempts his best Dick Van Dyke impersonation"),
                            Template("grabs his comb and whistles through it in the vain hope of making a tune. Resorts to playing $choons"),
                            Template("grabs the maracas and plays along with $choon"),
                            Template("gets his trusty Roland 101 and attempts to play $choon"),
                            Template("uncovers the modular synth and settles in for a 2 hour noodle session"),
                            Template("taps dances the theme to Batman"),
                            Template("sings like a frog for $name"),
                            Template("turns on the 808 drum machine and looks pensive"),
                            Template("suggests to $name that they perform $choon together on the piano"),
                            Template("claps his hands"),
                            Template("(music) $choon"),
                            Template("(music) $choon"),
                            Template("shouts !drink in a Scottish accent"),
                            Template("taps out the Great Escape on the bar"),
                            Template("switches on the dusty 1210s and grabs $choon"),
                            Template("plays $choon and turns it up to 11"),
                            Template("raises the ghost of John Peel and plays $choon to him"),
                            Template("turns off all the lights and leaves you all with $choon."),
                            Template("turns on the disco floor and plays $choon."),
                            Template("appears dressed as $name just as the speakers blurt out $choon."),
                            Template("jumps in through the window to the sound of $choon."),
                            Template("pats $name on the back and heads to the bar - $choon plays quietly in the background"),
                            Template("clicks his fingers and $choon brings the stereo alive again"),
                            Template("would like to remind $name what happen last time when we had $choon on the radio."),
                            Template("laughs at $name's dress code and pops $choon on the steampunk gramaphone"),
                            Template("shouts to everyone this (mooning) is not a laughing matter and puts on $choon"),
                            Template("walks in wearing $name's slippers and plays $choon"),
                            Template("comes out from the cupboard with Pambot and quickly plays $choon"),
                            Template("high 5's $name and puts on $choon"),
                            Template("glares at @topfife and $name and reluctanty plays $choon"),
                            Template("points out that he's on the phone ordering more cheese."),
                            Template("shouts up that he's in the cellar and for $name to play $choon"),
                            Template("reminds $name that it's his turn to choose $choon"),
                            Template("scoffs at $name's hiphop favourites and serves up $choon"),
                            Template("walks in wearing $name's sunglasses and serves up $choon"),
                            Template("pops up behind the bar just as the stero blurts out $choon"),
                            Template("sighs and plays $choon"),
                            Template("orders himself to have a !drink and plays $choon"),                                           
                            Template("uncontrollably crys and plays $choon"),
                            Template("opens the windows as the volume comes up on $choon"),
                            Template("winks at $name and plays $choon"),
                            Template("glares at Marcus and Greg and grins, slipping on $choon"),
                            Template("looks blankly at $name and plays $choon"),
                            Template("cranks up the volume for $choon"),
                            Template("plays 10seconds of $choon"),
                            Template("plays $choon and backflips out of the bar"),
                            Template("puts on $choon and pours himself a murky pint"),
                            Template("switches over to $choon and pours himself a glitchy whisky"),
                            Template("plays $choon and pours himself a glitchy sherry"),
                            Template("plays $choon and pours himself a glitchy whisky"),
                            Template("plays $choon and salutes you all"),
                            Template("puts on the DVD of $choon and heads to the toilet"),
                            Template("sniggers at $name and plays $choon"),
                            Template("ignores $name and takes a tape cassette from Marcus' jacket and play $choon"),
                            Template("switches on the Karaoke machine - first up is $name with $choon"),
                            Template("turns on the dusty Tesla coil and warms up $choon"),
                            Template("leaves the bar to the sound of $choon"),
                            Template("flips open his shiny new macbook and plays $choon"),
                            Template("kicks the jukebox and up comes $choon"),
                            Template("stares at the jukebox and it magically plays $choon"),
                            Template("starts to pogo with $name to $choon"),
                            Template("shaves his head and plays $choon"),
                            Template("necks a vodka and plays $choon"),
                            Template("finishes $name's Snickers Bar and plays $choon"),
                            Template("jumps up and the bar and wiggles his hips to $choon"),
                            Template("gets tearful as he puts $choon on repeat."),
                            Template("gets tearful as he switches off $choon"),
                            Template("!snack"), 
                            Template("(drunk)"),  
                            Template("(poolparty)(poolparty) $choon (poolparty)(poolparty)"),  
                            Template("slips on $choon and lands on his arse"),  
                            Template("ignores $name and asks Pambot the time."),
                            Template("reminds himself he hasn't played $choon for ages."),
                            Template("buys $name a drink and plays loudly $choon"),
                            Template("gets a poem out of his back pocket and plays $choon"),
                            Template("sniffs and calls up $choon on his iphone"),
                            Template("gets out his iPhone and dials in $choon"),
                            Template("gets out his Pebble watch and dials in $choon"),
                            Template("reminds everyone about happy hour and plays $choon"),
                            Template("winks at Pambot and plays $choon"),
                            Template("gives $name a dry slap & plays $choon to teach $name a lesson"),
                            Template("flicks through the CD collection and quietly slips $choon on the hifi"),
                            Template("turns on the bass woofer and plays "),
                            Template("convinces himself he hasn't played $choon for ages"),
                            Template("mumbles something something punk and plays $choon"),
                            Template("turns to Pambot and ask's her to find $choon"),
                            Template("leaves a note for Rob Myers about the fabbing mess he made last night and plays $choon"),
                            Template("shouts 'Drinks on the House!' and celebrates with $choon"),
                            Template("remembers his ex-wifes mix tape and plays $choon"),
                            Template("turns on the TV to discover $choon"),
                            Template("turns off the TV and plays $choon"),
                            Template("plays $choon and rolls his eyes at $name"),
                            Template("pretends not to hear $name and puts on $choon"),
                            Template("drops $choon and returns to the cellar"),
                            Template("downloads $choon and finishes stocking the fruit juices"),
                            Template("plays $choon and swaggers off to the pantry"),
                            Template("suggest $choon and mutters something about the !cheese delivery"),
                            Template("drops $choon and slowly sways into a trance with $name"),
                            Template("drops $choon and immediately passes out"),
                            Template("slips into his Wrestling outfit and plays $choon"),
                            Template("looks up at $name and suggests $choon"),
                            Template("lobs a dolphin at $name and plays $choon"),
                            Template("taps the cd player and plays $choon"),
                            Template("proudly holds up a scruffy album cover and plays $choon"),
                            Template("has a ponder and settles for $choon"),
                            Template("emerges from the kitchen with a frying pan of $choon and serves it up to $name with a little mayo"),
                            Template("emerges from the kitchen with a plate of $choon and serves it up to $name with a little lemon grass"),
                            Template("emerges from the kitchen with a pot of $choon and serves $name a miserable portion"),
                            Template("phones a friend and goes for $choon"),
                            Template("shakes the snow globe and blasts out $choon"),
                            Template("falls to his knees and proclaims that he's losing his edge http://www.youtube.com/results?search_query=losing+my+edge+live "),
                            Template("asks 'who has got a match?' http://www.youtube.com/watch?v=EHJmPcILfg8"),
                            Template("takes a sad song and makes it better http://www.youtube.com/watch?v=GEKgYKpEJ3o"),
                            Template("wanders in from a haze and apologises for kissing the sky http://www.youtube.com/watch?v=SQ7dJ_hmorA"),

                            
                            Template("backspins along the bar and asks $name to put on $choon") ]

        self.choons = [ "a massive slap of techno http://www.last.fm/tag/techno/tracks",
            "the best in classic (rock) rock http://www.last.fm/tag/classic+rock/tracks",
            "the greatest smooth 8-) jazz 8-) sax http://www.last.fm/tag/saxophone+jazz",
            "some righteous, drug-free punk http://www.last.fm/tag/straight+edge",
            "knuckle-dragging, bong-huffing stoner metal http://www.last.fm/tag/stoner+metal",
            "a bucket of !w3t 5pl45y mischief http://www.last.fm/tag/seapunk/tracks",
            "some rather large beats. http://www.last.fm/tag/big%20beat/tracks",
            "some mental (bandit) acid http://www.last.fm/tag/acid%20house/tracks",
            "some creepy shit (poolparty) http://www.last.fm/tag/haunting/tracks",
            "an open-shirted, sandle-wearing heap of harmonies from Yacht Rock http://www.last.fm/tag/yacht+rock",
            "some hip swinging broadway (dance) (dance) (dance) (dance) (dance)  http://www.last.fm/tag/showtunes/tracks",
            "some fine rare Norse groove http://www.last.fm/music/I+Shot+The+Duck+Hunt+Dog/_/Techno+Viking",
            "MeRzB0W!!!!!! http://www.last.fm/music/Merzbow (rock)(rock)(rock)(rock) ",
            "(flag:de) GERMAN TECHNO http://www.last.fm/tag/german+techno/tracks",
            "popular football anthems http://www.last.fm/tag/football/tracks",
            "football anthems http://www.last.fm/tag/football/tracks",
            "vaguely Dave Clarke sounding techno http://www.last.fm/music/Dave+Clarke/+similar",
            "a bunch of properly wanged-up glitchcore http://www.last.fm/music/V%2FVm/+similar",
            "a little ska http://www.last.fm/tag/ska/tracks.",
            "some old time fun http://open.spotify.com/user/zeuclas/playlist/102eZ3tiE87QOpOdnh0vax",
            "some dope beats http://www.last.fm/music/Basic+Channel/+tracks.",
            "real Jamican dancehall videos. http://www.last.fm/tag/dancehall/videos.",
            "riddims from Banton http://www.last.fm/music/Buju+Banton/+tracks",
            "abstract techno madness http://www.last.fm/music/Autechre/+tracks (smoke)",
            "some (poolparty) Gabba with a donk in it http://www.youtube.com/results?search_query=donk+gabba",
            "Botstep and calls out Bausola a marketing whore. http://soundcloud.com/botstep-test-account",
            "a bit of Swedish delight http://www.last.fm/tag/swedish",
            "some classic Floyd http://www.last.fm/music/Pink+Floyd/_/Comfortably+Numb",
            "sarf lundin grime http://www.last.fm/tag/grime/tracks",
            "some glowing Sun Electric http://open.spotify.com/album/5WbeQHkkzc1ujONrZbrBs1",
            "bollywood bests http://www.last.fm/tag/bollywood/tracks",
            "some hillbilly genius http://soundcloud.com/bluegrass",
            "a couple of bleepy 8bit happy joys http://soundcloud.com/search?q%5Bfulltext%5D=8bit",
            "the latest goth rap. For realz. http://soundcloud.com/search?q%5Bfulltext%5D=goth+rap",
            "some chap rap http://www.youtube.com/results?search_query=chap+rap",
            "Blue Monday, again. http://www.youtube.com/watch?v=VyoDbX1EkPQ",
            "Joe Le Taxi http://www.youtube.com/watch?v=TD6O-HxowiI",
            "someting way too slow http://soundcloud.com/tracks/search?q%5Bfulltext%5D=800+slower",
            "the latest choon with a Donk in it http://soundcloud.com/tracks/search?q%5Bfulltext%5D=donk",
            "Riot Nation - Abba Gabba http://www.youtube.com/watch?v=7UZqnydWxEA",
            "The Walrus of Love http://www.youtube.com/watch?v=FWobeyZNTSM",
            "something a bit Egyption and a bit French http://www.last.fm/music/Dalida/+tracks",
            "some digi-harps http://www.last.fm/music/Jean-Michel+Jarre/+tracks",
            "something labelled funny http://soundcloud.com/search?q%5Bfulltext%5D=funny",
            "a dash of bluegrass http://www.last.fm/tag/bluegrass/tracks",
            "some rare groove. http://www.last.fm/tag/rare%20groove/tracks",
            "a classic 80's ballard http://www.youtube.com/watch?v=HTUqjVDTnnY",
            "some Maiden http://www.youtube.com/results?search_query=iron+maiden",
            "half a track of (fubar) http://www.last.fm/music/V%2FVm/+tracks",
            "something better than that last Kode9 attempt http://www.last.fm/music/Kode9/+similar",
            "that song by Europe, again. http://www.youtube.com/watch?v=TcJ-wNmazHQ",
            "something for the (inlove) lovers (inlove) in the room (u)  http://www.last.fm/tag/love%20songs/tracks (h) ",
            "some of the new glitchy dubstep that the kids in Shoreditch really hate http://soundcloud.com/tracks/search?q%5Bfulltext%5D=glitchy+dubstep.",
            "The Soggy Bottom Boys http://www.last.fm/music/The+Soggy+Bottom+Boys/+tracks",
            "A bit of Barry http://www.last.fm/music/Barry+Manilow/+tracks",
            "some mates of Judas Priest http://www.last.fm/music/Judas+Priest/+similar",
            "one of those mixes by the Baron http://soundcloud.com/tracks/search?q%5Bfulltext%5D=dave%2Bclarke%2Btechno&q%5Btype%5D=&q%5Bduration%5D="  
            "Lucifer http://open.spotify.com/track/1yFfKSYrxQhiZMfzCO5OGy",
            "some proper party music http://open.spotify.com/track/1eIuD1gHB8TBO2IxPBrzL3",
            "some Billy Idol wannabes http://www.last.fm/music/Billy+Idol/+similar",
            "(bandit) http://www.last.fm/music/Drexciya/+tracks (bandit)",
            "the *very* best of Bob James http://open.spotify.com/album/7xpnMRLA9rOrUDVOcrCldk",
            "one of those concept albums by Bowie http://open.spotify.com/album/2ulI4YbNOuFK2jXB2EGgWf",
            "BLACK METAL RADIO http://open.spotify.com/artist/1Dt7cfRzxM8qPVa82jX9y5",
            "a hefty dose of euro electro http://open.spotify.com/artist/7q8turyJovAulnYMhaLrPe",
            "some dark radio http://open.spotify.com/artist/432R46LaYsJZV2Gmc4jUV5",
            "Pretty Vacant http://open.spotify.com/track/2jfy5umLwAO22PIaXjJWPu",
            "a beach song http://open.spotify.com/track/5DWYNAL7IFCKrWW7RfhIG4",
            "The Rat Pack http://open.spotify.com/artist/1Mxqyy3pSjf8kZZL4QVxS0",
            "(swear) (swear) (swear) (swear) http://open.spotify.com/artist/0dmPX6ovclgOy8WWJaFEUU",
            "Sidney, doing it his way http://open.spotify.com/track/3Lx7TcHWXlXdwxkxxZMETj",
            "some Justice http://www.youtube.com/watch?v=sERA_cpf3_w",
            "some wonky techno http://www.youtube.com/watch?v=dtglQxHYtQY",
            "the best TV theme tunes http://www.youtube.com/watch?v=AepyGm9Me6w&list=PLDFAD20C832EC7384&feature=plpp_play_all",
            "the Norwegen National Anthem http://open.spotify.com/track/6z0fJaRa5DhKtaTIRXKZbc",
            "Her Majesty's theme tune http://open.spotify.com/track/0vI7yiTtzP8Lj78lO3dqLc",
            "The Vatican National Anthem http://open.spotify.com/track/2sejH68Hm6t8M9tG0dlYLu",
            "some quirky melodies http://www.last.fm/tag/quirky/tracks",
            "all the UK No 1 Hits http://open.spotify.com/user/sjhunt/playlist/5q5IHvVcnBYP1Dr1nIwBPN",
            "something like a cheap Kylie http://www.last.fm/music/Kylie+Minogue/+similar"]

    def generate( self, name ):
        choon = random.choice( self.choons )
        template = random.choice( self.templates )
        message_out = template.substitute(name=name, choon=choon)
        return "/me %s" % message_out
