# coding=UTF-8
from string import Template
import random
from commandbase import BaseCommand

class PonderCommand( BaseCommand ):

    def __init__(self):
          
          BaseCommand.__init__( self )

          self.command_mappings = [ "ponder" ]

          self.templates = [  Template("Fortune favours the brave."),
Template("Fortune turns all things to the advantage of those on whom she smiles."),
Template("Every man is the architect of his own fortune. "),
Template("Luck is what happens when preparation meets opportunity."),
Template("Shallow men believe in luck, believe in circumstances. Real men believe in cause and effect."),
Template("Don\'t let your daughter-in-law eat your autumn eggplants."),
Template("A bad wife spells a hundred years of bad harvest."),
Template("One who chases after two hares won\'t catch even one."),
Template("Talk about things of tomorrow and the mice inside the ceiling laugh (Nobody knows what tomorrow might bring)."),
Template("Feed a dog for three days and it is gratefull for three years. Feed a cat for three years and it forgets after three days."),
Template("With the first glass a man drinks wine, with the second glass the wine drinks the wine, with the third glass the wine drinks the man."),
Template("It is the same life whether we spend it crying or laughing."),
Template("The hawk with talent hides its talons (The person who knows most often says least)."),
Template("Darkness reigns at the foot of the lighthouse. "),
Template("Art is the illusion of spontaneity. "),
Template("When you\'re thirsty it\'s too late to think about digging a well. "),
Template("When the character of a man is not clear to you, look at his friends. "),
Template("A bird does not sing because it has an answer. It sings because it has a song. "),
Template("A bit of fragrance clings to the hand that gives flowers. "),
Template("A book is like a garden carried in the pocket. "),
Template("A child\'s life is like a piece of paper on which every person leaves a mark. "),
Template("A diamond with a flaw is worth more than a pebble without imperfections. "),
Template("A fool judges people by the presents they give him. "),
Template("A rat who gnaws at a cat\'s tail invites destruction. "),
Template("Be the first to the field and the last to the couch. "),
Template("Do not remove a fly from your friend\'s forehead with a hatchet. "),
Template("He who is drowned is not troubled by the rain. "),
Template("One moment of gratitude for your predicament outweighs a lifetime of struggle"),
Template("Allow the quiet voice to decide"),
Template("Your ideas are not your own, they were all given to you by this civilisation, the opportunity is there to find your OWN but first you must have one.  "),
Template("Other humans need things from you, if you love the thing they need, truly, you will give it freely. Do not try to love other humans unless they love what you need. "),
Template("If a giant cat speaking to you doesn\'t convince you that the world is a magical place, then you are very wise. Now go, use that wisdom to pack your personality into the tiny box of your expectations."),
Template("trying to fix the consequences of ignorance in this world will never work. Allow it to run it\'s own course as you watch and, having put down your burdon, laugh and dance with the freedom that is your birthright. "),
Template("It does exactly what it says on the tin"),
Template("Skim milk does not come from skinny cows"),
Template("Only Smarties have the answer"),
Template("Only the best for the Captain\'s table"),
Template("You\'ll never put a better bit of butter on your knife"),
Template("You\'ll never put a better bit of butter on your knife"),
Template("Do you love anyone enough to give them your last Rolo"),
Template("If it doesn\'t get all over the place, it doesn\'t belong in your face"),
Template("It takes a tough man to make a tender chicken"),
Template("Put a smile on, put a smile on. Everybody come on, put a smile on"),
Template("Lipsmackin\' thirstquenchin\' acetastin\' motivatin\' goodbuzzin\' cooltalkin\' highwalkin\' fastlivin\' evergivin\' coolfizzin\'"),
Template("Away go troubles down the drain--Roto-Rooter."),
Template("I liked it so much I bought the company"),
Template("Maybe she\'s born with it, maybe it\'s Maybelline"),
Template("The lion leaps from strength to strength"),
Template("If only everything in life was as reliabale as a Volkswagen"),
Template("The future\'s bright. The future\'s Orange"),
Template("No battery is stronger longer"),
Template("There are some things money can\'t buy. For everything else, there\'s MasterCard"),
Template("Nothings sucks like an Electrolux"),
Template("Getting There Is Half The Fun"),
Template("Once driven, forever smitten"),
Template("The ultimate driving machine"),
Template("Because I\'m worth it."),
Template("Reach out and touch someone"),
Template("Cats like Felix like Felix"),
Template("Heineken refreshes the parts other beers cannot reach"),
Template("Where do you want to go today"),
Template("Hello Tosh, gotta Toshiba"),
Template("More doctors smoke Camels than any  other cigarette"),
Template("Nothing is more effective than Anadin"),
Template("I can\'t believe I ate the whole thing!"),
Template("You Too Can Have A Body Like Mine"),
Template("When you say Budweiser, you\'ve said it all."),
Template("Washing machines live longer with Calgon"),
Template("You\'ll be lovelier each day, with fabulous pink Camay"),
Template("The best tires in the world have Goodyear written all over them"),
Template("Don\'t live a little, live a lotto"),
Template("Keep hunger locked up til lunch"),
Template("I\'d rather die of thirst than drink from the cup of mediocrity"),
Template("Ready for tomorrow? Make sense of it with Norwich Union."),
Template("Guardian. Enriching the lives of people we touch."),
Template("Give your child an advantage for life"),
Template("Take away the risk and you can do anything."),
Template("Makita. It\'s All The Power You Need."),
Template("Inspired by babies. Created by Pampers"),
Template("Isn\'t it time you changed your nappy?"),
Template("Have a happy period. Always."),
Template("For millions of women the secret is TENA"),
Template("You can handle it. Germs can\'t"),
Template("Reveal the goddess in you."),
Template("Gillette. The Best a Man Can Get"),
Template("Take the feeling of clean to the Extreme"),
Template("Life\'s more interesting when you get Closer."),
Template("GlaxoSmithKline. Do more, feel better, live longer."),
Template("Good things come to those who wait"),
Template("Rozes. Expect the Unexpected and enjoy."),
Template("Get lost. Find yourself."),
Template("Life is harsh. Your tequila shouldn\'t be"),
Template("Great Tasting Wine with a Splash of Fruit                Just what you\'ve been looking for. "),
Template("Create your own Diet Coke break."),
Template("Tropicana\'s got the taste that shows on your face"),
Template("We all need a PG moment."),
Template("There are no facts, only interpretations. (Nietzsche)"),
Template("Do not look where you fell, but where you slipped."),
Template("A wise man never knows all, only fools know everything"),
Template("Indecision is like a stepchild: if he does not wash his hands, he is called dirty, if he does, he is wasting water."),
Template("Only a fool tests the depth of the water with both feet."),
Template("Whatever accomplishment you boast of in the world, there is someone better than you."),
Template("What you see in yourself is what you see in the world."),
Template("Don\'t show me the palm tree, show me the dates."),
Template("Only stretch your foot to the length of your blanket."),
Template("The sun at home warms better than the sun elsewhere."),
Template("If you fear God, you won\'t fear humans."),
Template("He who hesitates, regrets."),
Template("Don\'t put gold buttons on a torn coat."),
Template("Patience is the key to paradise."),
Template("No woman can make a wise man out of a fool, but every woman can change a wise man into a fool."),
Template("If you have a tail of straw, then keep away from the fire."),
Template("A dog that barks all the time gets little attention."),
Template("The world is a pot, man but a spoon in it."),
Template("You are as many a person as languages you know."),
Template("How can one start a fast with baklava in one\'s hand."),
Template("The eagle was killed by an arrow made from its own feathers."),
Template("Clouds that thunder do not always rain."),
Template("The hunt is like a dance for men, for the women the dance is the hunt."),
Template("What I do not know will not keep me warm."),
Template("A light is still a light-even though the blind man cannot see it."),
Template("If you shoot your arrows at stones, you will damage them."),
Template("The earth does not shake when the flea coughs."),
Template("One\'s own simple bread is much better than someone else\'s pilaf."),
Template("It\'s not shameful not to know, but it\'s shameful not to ask."),
Template("Cheap meat never makes a good soup."),
Template("Beauty is ten, nine of which is dressing."),
Template("Courage is ten, nine is the ability to escape."),
Template("The earth is a beehive; we all enter by the same door but live in different cells.."),
Template("The eye never forgets what the heart has seen."),
Template("A good deed will make a good neighbor."),
Template("Whenever I work hard for other people, I always sleep on an empty stomach."),
Template("No man can paddle two canoes at the same time."),
Template("The earth is a beehive; we all enter by the same door but live in different cells.."),
Template("The eye never forgets what the heart has seen."),
Template("A good deed will make a good neighbor."),
Template("Whenever I work hard for other people, I always sleep on an empty stomach."),
Template("No man can paddle two canoes at the same time."),
Template("Anyone who sees beauty and does not look at it will soon be poor."),
Template("Before you ask a man for clothes, look at the clothes that he is wearing."),
Template("Words are like spears: Once they leave your lips they can never come back."),
Template("There is no god like one\'s stomach; we must sacrifice to it every day."),
Template("A great affair covers up a small matter."),
Template("A brave man seldom is hurt in the back."),
Template("The eyes of all cheats are full of tears."),
Template("When an ant gets wings, it loses its head"),
Template("Two things rule the world -- reward and punishment."),
Template("Why would you use poison if you can kill with honey."),
Template("A wise man learns at the fool\'s expense."),
Template("He who knows nothing, doubts nothing."),
Template("The trees with most leaves will not necessarily produce juicy fruit."),
Template("Between the beginning and the end there is always a middle."),
Template("You can only take out of a bag what was already in it."),
Template("If you let everyone walk over you, you become a carpet."),
Template("If you wish to drown, do not torture yourself with shallow water."),
Template("Seize opportunity by the beard, for it is bald behind."),
Template("God promises a safe landing but not a calm passage."),
Template("Nature, time, and patience are the three great physicians."),
Template("Beware of a man\'s shadow and a bee\'s sting."),
Template("The blind person never fears ghosts."),
Template("One sesame seed won\'t make oil."),
Template("A stupid act entails doing the work twice over."),
Template("A hero only appears once the tiger is dead."),
Template("He who asks questions cannot avoid the answers."),
Template("A chattering bird builds no nest."),
Template("You come with a cat and call it a rabbit."),
Template("Rain does not fall on one roof alone."),
Template("By trying often, the monkey learns to jump from the tree."),
Template("A man should choose a friend who is better than himself. There are plenty of acquaintances in the world; but very few real friends."),
Template("A maker of idols is never an idolater."),
Template("A bird does not sing because it has an answer. It sings because it has a song."),
Template("A clever person turns great troubles into little ones and little ones into none at all."),
Template("A thorn defends the rose, harming only those who would steal the blossom."),
Template("When the bee comes to your house, let her have beer; you may want to visit the bee\'s house some day."),
Template("A pretty basket does not prevent worries."),
Template("A cat goes to a monastery, but she still remains a cat."),
Template("Little by little grow the bananas."),
Template("No matter how full the river, it still wants to grow."),
Template("When the sun rises, it rises for everyone."),
Template("Believe only half of what you see and nothing of what you hear."),
Template("What is new is pleasing and what is old is satisfying."),
Template("Life is short but a smile takes barely a second."),
Template("Listen to what they say of the others and you will know what they say about you."),
Template("Do not choose your wife at a dance, but in the field among the harvesters."),
Template("Wisdom is easy to carry but difficult to gather."),
Template("Better a lie which heals than a truth which wounds."),
Template("Nothing seems expensive on credit."),
Template("Do not protect yourself with a fence, but rather by your friends."),
Template("Better to ask twice than to lose your way once."),
Template("A lazy boy and a warm bed are difficult to part."),
Template("He who builds according to every man\'s advice will have a crooked house."),
Template("Give to a pig when it grunts and a child when it cries, and you will have a fine pig and a bad child."),
Template("A single bag of money is stronger than two bags of truth."),
Template("Learn politeness from the impolite."),
Template("When the angels present themselves, the devils abscond."),
Template("False ambition serves the neck."),
Template("A beautiful thing is never perfect."),
Template("The barking of a dog does not disturb the man on a camel."),
Template("Some men go through a forest and see no firewood."),
Template("A fool may ask more questions in an hour than a wise man can answer in seven years."),
Template("It is better to begin in the evening than not at all."),
Template("You never miss a slice from a cut loaf."),
Template("When a proud man hears another praised, he feels himself injured."),
Template("Advise and counsel him; if he does not listen, let adversity teach him."),
Template("What one hopes for is always better than what one has."),
Template("A single stick may smoke, but it will not burn."),
Template("The frog wanted to be as big as the elephant, and burst."),
Template("The witness of a rat is another rat."),
Template("Wait until it is night before saying it has been a fine day."),
Template("There is no pillow so soft as a clear conscience."),
Template("With enough ifs we could put Paris into a bottle."),
Template("Write injuries in sand, kindnesses in marble."),
Template("People count up the faults of those who keep them waiting."),
Template("He that will not look forward must look behind."),
Template("A dimple on the chin, the devil within."),
Template("He who would enjoy the fruit must not spoil the blossoms."),
Template("Even God cannot make two mountains without a valley in between."),
Template("Assurance is two-thirds of success."),
Template("The rooster said, I shall cry but whether the sun rises God knows."),
Template("The eyeless ant asked God: Give me eye-lashes."),
Template("God laughs at man\'s proposal."),
Template("You cackle in our place but you lay your eggs at someone else\'s place."),
Template("The cat which did not reach the sausage said: Anyhow it is Friday."),
Template("Too clever is stupid."),
Template("God gives the nuts, but he does not crack them."),
Template("Begin to weave and God will give the thread."),
Template("A lean agreement is better than a fat lawsuit."),
Template("Flatters, like cats, lick and then scratch."),
Template("No one tests the depth of the river with both feet."),
Template("Hunger is felt by a slave and hunger is felt by a king."),
Template("If there were no elephant in the jungle, the buffalo would be a great animal."),
Template("If things are getting easier, maybe you\'re headed downhill."),
Template("Only when you have crossed the river can you say the crocodile has a lump on his snout."),
Template("Great abilities produce great vices as well as virtues."),
Template("Men who have lost heart never yet won a trophy."),
Template("Men never moan over the opportunities lost to do good, only the opportunities to be bad."),
Template("Milk the cow, but do not pull off the udder."),
Template("The man on his feet carries off the share of the man sitting down."),
Template("When a needle falls into a deep well, many people will look into the well, but few will be ready to go down after it."),
Template("When you wait for tomorrow it never comes. When you don\'t wait for it tomorrow still comes."),
Template("Save your fowl before it stops flapping."),
Template("He who has done evil, expects evil."),
Template("First secure an independent income, then practice virtue."),
Template("Beyond the mountain is another mountain."),
Template("Ignorance doesn\'t kill you, but it does make you sweat a lot."),
Template("The pencil of God has no eraser."),
Template("If someone sweats for you, you change his shirt."),
Template("Don\'t insult the alligator until you\'ve crossed the river."),
Template("Teach thy tongue to say, I do not know.."),
Template("If a word be worth one shekel, silence is worth two."),
Template("A little fire burns up a great deal of corn."),
Template("He that eats till he is sick must fast till he is well."),
Template("Poverty is a wonderful thing. It sticks to a man after all his friends have forsaken him."),
Template("A man in this world without learning is as a beast of the field."),
Template("When a camel is at the foot of a mountain then judge of his height."),
Template("Among the blind, the squint rules."),
Template("When an elephant is in trouble even a frog will kick him."),
Template("Never strike your wife, even with a flower."),
Template("A prudent man does not make the goat his gardener."),
Template("The believer is happy; the doubter is wise."),
Template("When ambition ends, happiness begins."),
Template("Bargain like a gypsy, but pay like a gentleman."),
Template("A flatterer is a secret enemy."),
Template("Mediocrity is climbing molehills without sweating."),
Template("Useless wisdom is double foolishness."),
Template("All old sayings have something in them."),
Template("He who lives without discipline dies without honor."),
Template("Everyone wants to live long, but no one wants to be called old."),
Template("Life is a bridge. Cross over it, but build no house on it."),
Template("A person consists of his faith. Whatever is his faith, even so is he."),
Template("Don\'t bargain for fish which are still in the water."),
Template("Call on God, but row away from the rocks."),
Template("The cobra will bite you whether you call it cobra or Mr. Cobra."),
Template("Listening to good advice is the way to wealth."),
Template("A blind man who sees is better than a sighted man who is blind."),
Template("God provides, but He needs a nudge."),
Template("Every tear has a smile behind it."),
Template("Acquaintance without patience is like a candle with no light."),
Template("He who gets a name for early rising can stay in bed until midday."),
Template("Instinct is stronger than upbringing."),
Template("A trout in the pot is better than a salmon in the sea."),
Template("All sins cast long shadows."),
Template("The work praises the man."),
Template("To him that watches, everything is revealed."),
Template("To a quick question give a slow answer."),
Template("Better an egg today than a hen tomorrow."),
Template("Between saying and doing, many a pair of shoes is worn out."),
Template("The best armor is to keep out of range."),
Template("When you go to a donkey\'s house, don\'t talk about ears."),
Template("Words in mouth, no load upon head."),
Template("A little axe can cut down a big tree."),
Template("A man with trousers that are too short should wear long suspenders."),
Template("You can say anything to a man with a full stomach.You can\'t see the whole sky through a bamboo tube."),
Template("Time spent laughing is time spent with the gods."),
Template("Vision with action is a daydream; action without vision is a nightmare."),
Template("Fall seven times, stand up eight."),
Template("Never rely on the glory of the morning or the smiles of your mother-in-law."),
Template("Don\'t approach a goat from the front, a horse from the back, or a fool from any side."),
Template("Don\'t ask questions of fairy tales."),
Template("One of life\'s greatest mysteries is how the boy who wasn\'t good enough to marry your daughter can be the father of the smartest grandchild in the world."),
Template("When a habit begins to cost money, it\'s called a hobby."),
Template("Pray that you will never have to bear all that you are able to endure."),
Template("Life is like a lamp flame; it needs a little oil now and then."),
Template("Giving advice to a stupid man is like giving salt to a squirrel."),
Template("I bought the nettle, sowed the nettle, and then the nettle stung me."),
Template("Where there is sunshine, there is also shade."),
Template("Having a good discussion is like having riches."),
Template("He who does not know one thing knows another"),
Template("All cassavahs have the same skins but not all taste the same."),
Template("A person changing his clothing always hides while changing."),
Template("You may laugh at a friend\'s roof; don\'t laugh at his sleeping accomodation."),
Template("One man\'s beard is on fire, and another man warms his hands on it."),
Template("Words have no wings but they can fly many thousands of miles."),
Template("If you starve for three days, there is no thought that does not invade your imagination."),
Template("Carve the peg by looking at the hole."),
Template("You will hate a beautiful song if you sing it often."),
Template("Aim high in your career but stay humble in your heart."),
Template("It is more difficult to contend with oneself than with the world."),
Template("See with your mind, hear with your heart."),
Template("What the heart thinks, the mouth speaks."),
Template("Many will show you the way once your cart has overturned."),
Template("Do not throw the arrow which will return against you."),
Template("We lose the certain things, while we seek the uncertain ones."),
Template("Keep quiet and people will think you a philosopher."),
Template("Unless what we do is useful, glory is vain."),
Template("No gain is so certain as that which proceeds from the economical use of what you already have."),
Template("I don\'t want the cheese, I just want to get out of the trap."),
Template("Hygiene is two thirds of health."),
Template("His brains hang at the top of his fez."),
Template("Do today what you want to postpone until tomorrow."),
Template("No matter how fast the poplar grows, it will never reach heaven."),
Template("Lower your voice and strengthen your argument."),
Template("Distracted by what is far away, he does not see his nose."),
Template("It is better to refuse than to accept and not to go."),
Template("Words are like eggs: when they are hatched they have wings."),
Template("Nothing is so difficult that diligence cannot master it."),
Template("One does not like hot, the other does not like cold; make it tepid to make an agreement."),
Template("He who has learned how to steal, must learn how to hang."),
Template("A fool is like the big drum that beats fast but does not realize its hollowness."),
Template("To bend a bamboo, start when it is a shoot."),
Template("Do not measure another man\'s coat on your body."),
Template("The turtle lays thousands of eggs without anyone knowing, but when the hen lays an egg, the whole country is informed."),
Template("Far from the eye, far from the heart."),
Template("He who goes to bed hungry dreams of pancakes."),
Template("Where the heart loves, there the legs walk."),
Template("The evil weed produces the largest number of weeds."),
Template("The wallet of the timid man neither increases nor decreases."),
Template("As you see yourself, I once saw myself; as you see me now, you will be seen."),
Template("Never ask God to give you anything; ask Him to put you where things are."),
Template("He who strikes first, strikes twice."),
Template("It\'s not enough to know how to ride -- you must also know how to fall."),
Template("Envious persons never compliment, they only swallow."),
Template("Instruction in youth is like engraving in stone."),
Template("Reading books removes sorrows from the heart."),
Template("Evening promises are like butter: morning comes, and it\'s all melted."),
Template("If you don\'t understand it with a wink, you certainly will with a blow."),
Template("If you are a peg, endure the knocking; if you are a mallet, strike."),
Template("The seeds of the day are best planted in the first hour."),
Template("A handful of patience is worth more than a bushel of brains."),
Template("He who attempts too much seldom succeeds."),
Template("Little pots soon run over."),
Template("God does not pay weekly, but He pays at the end."),
Template("A cat will teach her young ones all the tricks, except how to jump backwards."),
Template("You cannot fly with wings made of butter."),
Template("Don\'t give a child a name until after it is born."),
Template("You eat an egg, but you don\'t understand how painful it was for the chicken."),
Template("The rainbow would be even more beautiful if the show was not for free."),
Template("Turn your face to the sun and the shadows fall behind you."),
Template("Boast during the day; be humble at night."),
Template("The block of wood should not dictate to the carver."),
Template("The more you ask how much longer it will take, the longer the journey will seem."),
Template("Persist as resolutely as you persist in eating."),
Template("If the owner of the goat is not afraid to travel by night, the owner of a hyena certainly will not be."),
Template("The cry of the hyena and the loss of the goat are one."),
Template("Abundance will make cotton pull a stone."),
Template("Every fault is laid at the door of the hyena, but it does not steal a bale of cloth."),
Template("Accomplishment of purpose is better than making a profit."),
Template("A man does not wander far from where his corn is roasting."),
Template("The death that will kill a man begins as an appetite."),
Template("The frog does not jump in the daytime without reason."),
Template("The man being carried does not realize how far away the town really is."),
Template("A tiger does not have to proclaim its tigritude."),
Template("It\'s no shame to look into the warm spring sun and regret a lost limb."),
Template("It\'s too bad to want a thing and not be allowed it."),
Template("In every woman there is a Queen. Speak to the Queen and the Queen will answer."),
Template("Rather a bit correctly than much incorrectly."),
Template("Luck is loaned, not owned."),
Template("You will not dare mistreat the face you see in the morning."),
Template("Away from the eye, away from the mind."),
Template("IF only I were a bird! Ah, but eating caterpillars?"),
Template("Sell what you have bought while the dust is still on your shoes."),
Template("Whatever is written on the forehead is always seen."),
Template("Don\'t trust in fortune until you are in heaven."),
Template("A clear conscience is far more valuable than money."),
Template("People who do not break things first will never learn to create anything."),
Template("If you make a habit of buying things you do not need, you will soon be selling things you do."),
Template("The rattan basket criticizes the palm leaf basket, still both are full of holes."),
Template("The greatest love is a mother\'s, then a dog\'s, then a sweetheart\'s."),
Template("There are a thousand paths to every wrong."),
Template("God grant me a good sword and no use for it."),
Template("Even a clock that is not going is right twice a day."),
Template("Under capitalism man exploits man; under socialism the reverse is true."),
Template("Beware of a man that does not talk and a dog that does not bark."),
Template("What was hard to bear is sweet to remember."),
Template("Hell is paved with good intentions, roofed in with lost opportunities."),
Template("Good management is better than good income."),
Template("Every peddler praises his own needles."),
Template("Do not put your spoon into the pot which does not boil for you."),
Template("If you wish good advice, consult an old man."),
Template("Eating and scratching want but a beginning."),
Template("Every sin brings its punishment with it."),
Template("A creaking door hangs long on its hinges."),
Template("There is no shame in not knowing; the shame lies in not finding out."),
Template("Success and rest don\'t sleep together."),
Template("For him who does not believe in signs, thre is no way to live in the world."),
Template("Acknowledgement is half of correction."),
Template("Pray to God, but keep rowing to the shore.He who has travelled alone can tell what he likes."),
Template("You can outdistance that which is running after you, but not what is running inside you."),
Template("Every cackling hen was an egg at first."),
Template("If you are building a house and a nail breaks, do you stop building, or do you change the nail?"),
Template("In a court of fowls, the cockroach never wins his case."),
Template("Gather the breadfruit from the farthest branches first."),
Template("Sit and wait for the good chestnuts."),
Template("A decision made at night may be changed in the morning."),
Template("You shake in vain the branch that bears no fruit."),
Template("Stones decay; words last."),
Template("A book is a garden carried in the pocket."),
Template("Fear not the man who fears God."),
Template("A promise is a cloud; fulfillment is rain."),
Template("A little and a little, collected together, becomes a great deal; the heap in the barn consists of single grains, and drop and rop makes an inundation."),
Template("A friend is known when needed."),
Template("If you don\'t see the bottom, don\'t wade."),
Template("When the heart is full the tongue will speak."),
Template("Be slow in choosing a friend but slower in changing him."),
Template("Never let your feet run faster than your shoes."),
Template("Get what you can and keep what you have; that\'s the way to get rich."),
Template("What\'s the use of consulting a dead man\'s horoscope?"),
Template("Nobody tells all he knows."),
Template("The opportunity that God sends does not wake up him who sleeps."),
Template("Even the fall of a dancer is a somersault."),
Template("If a centipede loses a leg, it does not prevent him from walking."),
Template("Walk with your slippers until you can find your shoes."),
Template("Who is blind, dumb and deaf will live a peaceful life of a hundred years."),
Template("Keep watch for the appearing mushroom."),
Template("Crooked wood is straightened with fire."),
Template("Only your real friends will tell you when your face is dirty."),
Template("I grew up among wise men and found that there is nothing better for man than silence."),
Template("An orange never bears a lime."),
Template("Knowledge is not the main thing, but deeds."),
Template("To try and fail is not laziness."),
Template("The big fish is caught with big bait."),
Template("Man\'s life is like a drop of dew on a leaf"),
Template("It is easier to believe than to go and ask."),
Template("Every road does not lead to Rome."),
Template("Speak the truth, but leave immediately after."),
Template("Never whisper to the deaf or wink at the blind."),
Template("Do not walk into a snake pit with your eyes open."),
Template("Wisdom does not come overnight."),
Template("In the ocean, one does not need to sow water."),
Template("Where I make my living, there is my home."),
Template("He who does not shave you does not cut you."),
Template("If you are looking for a fly in your food it means that you are full."),
Template("He who has no intelligence is happy with it."),
Template("The fool who owns an ox is seldom recognized as a fool."),
Template("No hill without gravestones, no valley without shadows."),
Template("You are not great just because you say you are."),
Template("He who goes with wolves learns to howl."),
Template("How beautiful it is to do nothing, and then rest afterward."),
Template("The beginning of health is to know the disease."),
Template("More things grow in the garden than the gardener sows."),
Template("If you can\'t bite, don\'t show your teeth."),
Template("There are three things which if one does not know, one cannot live long in the world: what is too much for one, what is too little for one, and what is just right for one."),
Template("Aiming isn\'t hitting."),
Template("Don\'t plant a seed in the sea."),
Template("If you destroy a bridge, be sure you can swim."),
Template("A fly does not mind dying in coconut cream."),
Template("Fear less, hope more, eat less, chew more, whine less, berathe more, talk less, say more, hate less, love more, and all good things will be yours."),
Template("God gives every bird his worm, but he does not throw it into the nest."),
Template("Those who wish to sing always find a song."),
Template("Don\'t throw away the old bucket until you know whether the new one holds water."),
Template("Sweep first before your own door, before you sweep the doorsteps of your neighbors."),
Template("When one shuts one eye, one does not hear everything."),
Template("Speech is silver; silence is golden."),
Template("One simple maxim is often worth more than two good friends."),
Template("When in doubt who will win, be neutral."),
Template("Better to sell with regret than to keep with regret."),
Template("The one who teaches is the giver of eyes."),
Template("Learn about the future by looking at the past."),
Template("Only the cure you believe in cures."),
Template("If you have planted a tree you must water it too."),
Template("IF you are buying a cow, make sure that the price of the tail is included."),
Template("We start as fools and become wise through experience."),
Template("The roaring lion kills no game."),
Template("Do not make the dress before the child is born."),
Template("Events follow one another like the days of the week."),
Template("Do not mend your neighbor\'s fence before seeing to your own."),
Template("Bald people can always find a comb."),
Template("Life is so short we must move very slowly."),
Template("With one stump you can\'t make a good fire."),
Template("Wait until the tree has fallen before you jump over it."),
Template("At high tide the fish eat ants; at low tide the ants eat fish."),
Template("A father deserted by a wise son is like being caught in a shower without a felt."),
Template("Goodness speaks in a whisper, evil shouts"),
Template("Any fool can say Ah -- you need intelligence to say Yes."),
Template("Eat according to the limits of your provisions; walk according to the length of your step."),
Template("To spread the news is to multiply it."),
Template("Even though you know a thousand things, ask the man who knows one."),
Template("Having two ears and one tongue, we should listen twice as much as we speak."),
Template("A person does not seek luck; luck seeks the person."),
Template("Coffee should be black as Hell, strong as death, and sweet as love."),
Template("Happiness is like crystal -- when it shines the most, it soon cracks."),
Template("He who hunts two rats, catches none"),
Template("A roaring lion kills no game."),
Template("A strawberry blossom will not moisten dry bread."),
Template("The hunter in pursuit of an elephant does not stop to throw stones at birds."),
Template("Caution is not cowardice; even the ants march armed."),
Template("The church is near, but the way is icy. The tavern is far, but I will walk carefully."),
Template("Your head is not only for putting a hat on"),
Template("Every disadvantage has its advantage."),
Template("Only when you have eaten a lemon do you appreciate what sugar is"),
Template("No matter how hard you try the bull will never give milk."),
Template("The early bird gets the worm."),
Template("Cunning men deal in generalizations."),
Template("Nobody has ever bet enough on a winning horse."),
Template("After all is said and done, more is said than done."),
Template("The more sins you confess, the more books you will sell."),
Template("If you want to gather a lot of knowledge, act as if you are ignorant."),
Template("There is one fish in the pond, and ten anglers on the bank."),
Template("Venture all; see what fate brings."),
Template("The higher you climb, the heavier you fall."),
Template("Better to die than to live on with a bad reputation."),
Template("Three things give us hardy strength: sleeping on hairy mattresses, breathing cold air, and eating dry food."),
Template("A spoon does not know the taste of soup, nor a learned fool the taste of wisdom."),
Template("Conscience is the nest where all good is hatched."),
Template("Your hand is never the worse for doing its own work."),
Template("Without perseverance talent is a barren bed."),
Template("If God wants people to suffer, he sends them too much understanding."),
Template("If you want your dreams to come true, don\'t over sleep."),
Template("Before you start up a ladder, count the rungs."),
Template("If a link is broken, the entire chain breaks."),
Template("He who can\'t endure the bad will not live to see the good."),
Template("Life is like a game in which God shuffles the cards, the devil deals them and we have to play the trumps."),
Template("One ounce of good luck is better than a ton of brains."),
Template("No one likes to be the first to step on the ice."),
Template("A good rest is half the work."),
Template("If you wish to know what a man is, place him in authority."),
Template("If you understand, things are just as they are; if you do not understand, things are just as they are."),
Template("Sitting quietly, doing nothing, spring comes and the grass grows by itself."),
Template("Do not seek the truth, only cease to cherish your opinions."),
Template("Only when you can be extremely pliable and soft can you be extremely hard and strong."),
Template("The obstacle is the path."),
Template("If you can walk you can dance. If you can talk you can sing."),
Template("Two experts never agree."),
Template("We will be grateful to flowers only if they have born fruits."),
Template("Whoever plows with a team of donkeys must have patience."),
Template("A coward has no scar."),
Template(" If you want to go fast, go alone; if you want to go far, go together   - African proverb"),
Template("Misery is almost always the result of thinking.  (Joubert)"),
Template("God has no religion. (Ghandi)"),
Template("Know thyself.  "),
Template("QUESTIONS ARE ALIVE BUT ANSWERS ARE DEAD."),
Template("this is a test"),
Template("The big bang is an ongoing explosion of space AND time so right now you are at the leading edge of the universe. "),
Template("If you are going to jump in, jump in where the water is deep."),
Template("Your highest thoughts and your basest desires are both mirrors of your true feelings."),
Template("The swifts are off to Africa. Look high in the sky next May."),
Template("Listen. What do you hear? Listen again."),
Template("The swift finds a kind curve in the most inauspicious wind."),
Template("For self-help one does not need a book; one needs a self."),
Template("For hope to carry on many false hopes may have to be smashed."),
Template("That the infinite is unknowable gives us the blessing of eternal wonder."),
Template("It\'s behind you!"),
Template("The truth is everywhere. If it wasn\'t it wouldn\'t be the truth."),
Template("Peace is the ground beneath all struggle."),
Template("The earth aches before it bursts into life."),
Template("All need empowerment but none can hold onto power."),
Template("It can be more of a shock to not be in shock because normal existence is shocking."),
Template("Individuals can learn to live without other individuals but people\'s first need is people."),
Template("The full moment has reason leading to it, purpose leading from it and meaning within it."),
Template("You weren\'t expecting this were you?"),
Template("Everything I say is a lie."),
Template("Denial is the first response to trauma. It can\'t last."),
Template("Good sex starts before the first touch and lingers beyond the last."),
Template("A man\'s greatest weakness is his ego; his greatest strength is his ego."),
Template("A woman\'s greatest weakness is the flow; her greatest strength is the flow."),
Template("Fish do need bicycles, much more than cars."),
Template("You can live with them, and you can live without them."),
Template("Women are brought to their knees every month; men need church or sport or combat."),
Template("Your body is a gift of the earth; in the end you will give it back."),
Template("Your mind is a gift of time; it will, in time, be still."),
Template("Love is a gift of forever; it is no one\'s to take away."),
Template("Love everyone, even trainspotters."),
Template("The pain of love is not love; it is the stripping away of everything else."),
Template("You put your whole self in, your whole self out, in, out, in, out, you shake it all about, you do the hokey cokey and you turn  around; that\'s what it\'s all about."),
Template("Don\'t knock it until you\'ve tried it, and when you\'ve tried it, still don\'t knock it."),
Template("Family provide the canvas and paints; the individual is the artist."),
Template("When you are ready to sacrifice all for another, you have laid the foundation of family."),
Template("Everyone in the world may be to you your parent, your sibling, your child."),
Template("I don\'t care too much for money; money can\'t buy me love."),
Template("Love don\'t get everything, it\'s true; what it don\'t get I can\'t use."),
Template("Money is for using; people are not."),
Template("When making money make merry. "),
Template("Easy come, easy go. Harder gains make seeds to sow."),
Template("Your ship will come in when the tide is right and the wind is fair."),
Template("Love your work and every penny seems a bonus."),
Template("Save the harvest of the fat years, but don\'t let it rot."),
Template("Give what you\'ve got, don\'t blag what you\'ve not."),
Template("Make it up as you go along."),
Template("You learn what you want to do while you are doing."),
Template("A square peg needs to find a square hole, or make one."),
Template("Tell the world you\'re great and some might believe you; build a reputation and the word will spread itself."),
Template("When you are doing what you should be doing, it\'s like you are a magician channelling the energy of the universe."),
Template("Is it worth the struggle? If it is, relish it, like sport with a respected rival."),
Template("Magnificent dreams may take time to make real."),
Template("Whatever you do, do it good."),
Template("Do something, even if it\'s nothing."),
Template("The essence of your dreams unfolds in the most mundane of realities."),
Template("Listen and you will hear the word."),
Template("Does God exist? Yes? No? Probably? If I tick any box I diminish the divine to the size of my ego."),
Template("Gods are personifications of abstract nouns like beauty, wisdom and power. The one true God is all of these, (the abstract-noun-ness of abstract nouns.)"),
Template("All that we know of death is that which we face in life."),
Template("All that we know of God is that which we see in ourselves."),
Template("I like this moment, and look forward to the next."),
Template("You know as well as anyone."),
Template("Don\'t expect answers from a God of love; don\'t expect anything but love."),
Template("You cannot think your way, work your way or fight your way to God, but God may reach out to you, touch you, inspire you."),
Template("A loving God would be pleased that you recognised the miraculous wonders of the world whether you praised with art or science or devotion."),
Template("God is a delusion; Father Christmas is an illusion; Love is an illusion; this is an illusion. Does that help?"),
Template("God IS The Good Idea."),
Template("God will not shout to make you take notice; God will be whispering when you are still enough to hear."),
Template("It is the spirit that survives."),
Template("If everyone brings what they can to the market; no one goes home empty-handed."),
Template("Your culture, like your feelings, can never be dismissed."),
Template("Opinions, like your thoughts, can be mistaken, but let\'s hear them."),
Template("Freedom means being able to choose between the rock and the hard place."),
Template("Freedom is a song when you are knocked out on penalties."),
Template("Freedom is courage."),
Template("Freedom is never needing to lie."),
Template("Freedom is singing the song of the sun in the rain."),
Template("Freedom is both acceptance and the will to carry on."),
Template("It could happen to anyone, literally or metaphorically."),
Template("No one knows what it is to be human any more than you."),
Template("If you want to defeat your enemy sing their song; if you want to make peace sing along."),
Template("Experience does not make opinions more valid."),
Template("All have a right to be heard and a responsibility to listen."),
Template("The world equally needs builders, explorers, directors and negotiators."),
Template("High Court Judge, high school kid or high as a kite, an opinion is an opinion."),
Template("A mind is like a parachute - it doesn\'t work if it\'s not open -- Frank Zappa"),
Template("Love is metaphysical gravity. (Fuller)"),
Template("Art is love.  (Hunt)"),
Template("Love is a snowmobile racing across the tundra and then suddenly it flips over, pinning you underneath.  At night, the ice weasels come.  (Groening)"),
Template("Cats are intended to teach us that not everything in life has a function.  (Keillor)"),
Template("Happiness is good health and a bad memory.  (bergman)"),
Template("In heaven all the interesting people are missing.  (Nietzsche)"),
Template("Almost every wise saying has an opposite one, no less wise, to balance it."),
Template("It is not easy to stop thinking ill of others. Usually one must enter into a friendship with a person, who has accomplished that great feat herself. Then, something might start to rub off on you."),
Template("First the fish needs to say: \'something ain\'t right about this camel ride-And I\'m feeling so damn thirsty\'"),
Template("God blooms from the shoulder of the elephant who becomes courteous to the ant"),
Template("Blame, keeps the sad game going. It keeps stealing all your wealth: Giving it to an imbecile with no financial skills."),
Template("It is not easy to stop thinking ill of others. Usually one must enter into a friendship with a person, who has accomplished that great feat herself. Then, something might start to rub off on you."),
Template("when the winners lose their swagger ,you know something has evened the playing field"),
Template("it would be easier to roll up the entire sky into a small cloth than it would be to obtain true happiness without knowing the self "),
Template("know that all of nature is but a magic theatre, that the great mother is the master magician,and that this whole world is peopled by her many parts"),
Template("we are like the spider. we weave our life and then move along in it"),
Template("we are like the dreamer who dreams and then lives in the dream"),
Template("why don\'t we do it in the road?"),
Template("please ensure all baggage is stored in the overhead compartment"),
Template("that\'s life, that\'s what all the people say"),
Template("you\'re riding high in april, shot down in may"),
Template("students who achieve oneness will move on to twoness"),
Template("wealth is better that poverty. if only for financial reasons"),
Template("life is full of misery, loneliness and suffering."),
Template("and it\'s all over much too soon"),
Template("it seems the world is divided into good and bad people.the good ones sleep better were as the bad ones seem to enjoy the waking hours much better"),
Template("the spirit never grows old"),
Template("This little light o\' mine, I\'m gonna let it shine,"),
Template("the more you think, the more you stink"),
Template("an old wise fish swims past two younger fish"),
Template("as he passes by, he says \'mornin boy\'s - how\'s the water today\'"),
Template("after he has gone the two turn to each other and one says \'what\'s water?\'"),
Template("We have all, the time in the world"),
Template("Time enough for life"),
Template("To unfold"),
Template("All the precious things"),
Template("Love has in store"),
Template("we have all the love in the world"),
Template("if that\'s all we have, you will find, we need nothing more"),
Template("time is an illusion. lunchtime - doubly so"),
Template("the answer to the ultimate question of life the universe and everything......is 42"),
Template("A good horse runs even at the shadow of the whip"),
Template("the statement I am making now.........is a lie"),
Template("if you want to feel rich, just count the things you have that money can\'t buy"),
Template("when spider webs unite, they can tie up a lion"),
Template("enjoy yourself, it\'s later than you think"),
Template("nothing\'s impossible, I have found "),
Template("for when my chin is on the ground,"),
Template("I pick myself up, dust myself off, and start all over again."),
Template("anyone who thinks money will make you happy hasn\'t got money."),
Template("In a cat\'s world, all things belong to cats"),
Template("Beware of people who dislike cats"),
Template("The man who loves cats will love his wife"),
Template("A cat is a puzzle for which there is no solution."),
Template("look closely at your surroundings"),
Template("you are what you think about all day long"),
Template("to lower your stress level, get a cat"),
Template("life is not a struggle, it\'s a wiggle"),
Template("a woman who seeks to be equal with men lacks ambition"),
Template("because of your melodic nature, the moonlight never misses an appointment"),
Template("the onion you are eating is someone else\'s water lily "),
Template("trust your intuition. the universe is guiding your life"),
Template("DON\'T PANIC"),
Template("something you lost will soon turn up"),
Template("as the purse is emptied, the heart is filled"),
Template("be mischievous and you will not be lonesome"),
Template("he who laughs at himself can never run out of things to laugh at"),
Template("if you want the rainbow, you must put up with the rain"),
Template("if you always give, you will always have"),
Template("everything changes, everything you can perceive is in constant flux. the only thing that never changes.........is you"),
Template("if you would be loved, then love and be lovable "),
Template("love is like wildflowers......it is often found in the most unlikely places"),
Template("pain is weakness leaving the body"),
Template("there is no coming to consciousness without pain"),
Template("that which is escaped now, is pain to come"),
Template("the great painter michelangelo said \'everything hurts\' "),
Template("The injuries that befall us unexpectedly are less severe than those which are deliberately anticipated"),
Template("no pain no gain"),
Template("Pain nourishes courage. You can\'t be brave if you\'ve only had wonderful things happen to you"),
Template("Pain pays the income of each precious thing"),
Template("No pain, no palm; no thorns, no throne; no gall, no glory; no cross, no crown"),
Template("Remember that pain has this most excellent quality. If prolonged it cannot be severe, and if severe it cannot be prolonged"),
Template("The pain of the mind is worse than the pain of the body"),
Template("Pleasure that is obtained by unreasonable and unsuitable cost, must always end in pain"),
Template("one is judged by the company one keeps"),
Template("I am convinced we do not only love ourselves in others but hate ourselves in others too"),
Template("There are two types of people. Those we who come into a room and say, \'\'Well, here I am!\'\' and those who come in and say, \'\'Ah, there you are.\'\'"),
Template("When you look for the best in others, you bring out the best in yourself "),
Template("In each of us there is a little of all of us"),
Template("better to Have People Hate you For Who you are Than Love you For Who you\'re Not"),
Template("Some people can stay longer in an hour than others can in a week"),
Template("Only a few human beings should grow to the square mile; they are commonly planted too close"),
Template("  Unhurt people are not much good in the world"),
Template("We are the people our parents warned us about"),
Template("The rich would have to eat money if the poor did not provide food"),
Template("Money is something you got to make in case you don\'t die"),
Template("an ass laden with gold is still an ass"),
Template("A grain of gold will gild a great surface, but not so much as a grain of wisdom"),
Template("The only wealth is life"),
Template("you love someone, not for what they are, but for what you are when you are with them"),
Template("The hottest love has the coldest end"),
Template("Some of the greater things in life are unseen, that\'s why you close your eyes when you kiss, cry, or dream..."),
Template("Don\'t let someone become your everything, because when they\'re gone you have nothing! "),
Template("if you\'re having a bad day, know this. the mayfly lives only one day, and sometimes it rains"),
Template("If people stand in a circle long enough, they\'ll eventually begin to dance"),
Template("If you love someone, set them free; if they come back, set them on fire"),
Template("be still and know god"),
Template("It is not easy to stop thinking ill of others. Usually one must enter into a friendship with a person, who has accomplished that great feat herself. Then, something might start to rub off on you.")
]

    def generate( self, name ):
        template = random.choice( self.templates )
        message_out = template.substitute(name=name)
        return "/me scratches his beard and says '%s'" % message_out

